### ISSUE TITLE
Trying to pair with mac - unable to download the SDK version

### ISSUE THREAD

**Issue by arizvi-techgies** [dotnet/install-scripts#407]
I am trying to Pair it with Mac from my Windows and have VS2022 17.7.6

MacOS Sonoma 14.0
Xcode 15
.NET 7.0.403 installed on MacOS

Below are the logs. When trying to Pair Mac, the URL it's trying to download doesn't contain the file.

Installing dotnet SDK '7.0.403-servicing.23520.24'...
Downloading dotnet-install script...
Using dotnet install script '/Users/adeelrizvi/Library/Caches/Xamarin/XMA/SDKs/dotnet/scripts/dotnet-install.sh'...
--install-dir /Users/adeelrizvi/Library/Caches/Xamarin/XMA/SDKs/dotnet --version 7.0.403-servicing.23520.24 --architecture Arm64 --no-path
dotnet-install: Attempting to download using primary link https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/dotnet-sdk-7.0.403-servicing.23520.24-osx-arm64.tar.gz
curl: (22) The requested URL returned error: 404
dotnet-install: The resource at primary link 'https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/dotnet-sdk-7.0.403-servicing.23520.24-osx-arm64.tar.gz' is not available.
dotnet-install: Attempting to download using legacy link https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/dotnet-dev-osx-arm64.7.0.403-servicing.23520.24.tar.gz
curl: (22) The requested URL returned error: 404
dotnet-install: The resource at legacy link 'https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/dotnet-dev-osx-arm64.7.0.403-servicing.23520.24.tar.gz' is not available.
dotnet-install: Attempting to download using primary link https://dotnetbuilds.azureedge.net/public/Sdk/7.0.403-servicing.23520.24/dotnet-sdk-7.0.403-servicing.23520.24-osx-arm64.tar.gz
curl: (22) The requested URL returned error: 404
dotnet-install: The resource at primary link 'https://dotnetbuilds.azureedge.net/public/Sdk/7.0.403-servicing.23520.24/dotnet-sdk-7.0.403-servicing.23520.24-osx-arm64.tar.gz' is not available.
dotnet-install: Attempting to download using legacy link https://dotnetbuilds.azureedge.net/public/Sdk/7.0.403-servicing.23520.24/dotnet-dev-osx-arm64.7.0.403-servicing.23520.24.tar.gz
curl: (22) The requested URL returned error: 404
dotnet-install: The resource at legacy link 'https://dotnetbuilds.azureedge.net/public/Sdk/7.0.403-servicing.23520.24/dotnet-dev-osx-arm64.7.0.403-servicing.23520.24.tar.gz' is not available.
Could not install dotnet SDK '7.0.403-servicing.23520.24'. Details: dotnet_install: Error: Could not find `.NET Core SDK` with version = 7.0.403-servicing.23520.24

**Comment by baronfel** [comment]
@rbhanda can you check to make sure the servicing releases got to the relevant buckets?

**Comment by rbhanda** [comment]
Hi, I found an issue with our automation. This should be fixed now.

**Comment by baronfel** [comment]
Thank you @rbhanda!

**Comment by YuliiaKovalova** [comment]
Hi @arizvi-techgies ,

Could you verify if this issue is still relevant for you?
Thank you!

**Comment by arizvi-techgies** [comment]
@YuliiaKovalova, it works!!! Thank you so much now my pc is paired with my mac

**Comment by ImGonaRot** [comment]
This issue is closed but it still does not work on a MAC.
If user attempts to download the latest dotnet-install.sh from https://dot.net/v1/dotnet-install.sh into there ~/Library/Caches/Xamarin/XMA/SDKs/dotnet/scripts and then run "sudo sh dotnet-install.sh --install-dir /Users/U/Library/Caches/Xamarin/XMA/SDKs/dotnet --version 7.0.403-servicing.23520.24 --architecture Arm64 --no-path" they will get 401 file not found.
If the user tries to look at the actual gz, it is empty https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/dotnet-sdk-7.0.403-servicing.23520.24-osx-arm64.tar.gz

**Comment by YuliiaKovalova** [comment]
Hi @rbhanda , 
Could you help with the @ImGonaRot  issue?

**Comment by rbhanda** [comment]
this is weird, I can download from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/7.0.403-servicing.23520.24/dotnet-sdk-7.0.403-osx-arm64.tar.gz but not from https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/dotnet-sdk-7.0.403-servicing.23520.24-osx-arm64.tar.gz . I am purging the CDN cache to see if that will help

**Comment by YuliiaKovalova** [comment]
@ImGonaRot, the specified path doesn't return an archive because for this specific package, intstall scripts resolve sdk from a different location: https://dotnetcli.blob.core.windows.net/dotnet/Sdk/7.0.403-servicing.23520.24/dotnet-sdk-7.0.403-osx-arm64.tar.gz .
The script uses a multilevel probing approach.

**Comment by ImGonaRot** [comment]
@YuliiaKovalova  Thanks for the information. I'm not sure how to proceed. Both I and my coworker are stuck on Pair to Mac.
He is running VS 17.7.4 and I am running VS 17.7.6.
I just thought I could try to manully install this on the Mac but that doesn't seem to work.

**Comment by YuliiaKovalova** [comment]
@ImGonaRot, please describe step by step what you are trying to do with -vebose logs attached.

**Comment by ImGonaRot** [comment]
@YuliiaKovalova  This is what it logs in Output > Xamarin window

Xamarin - 17.7.0.223-d17-7+c374b3e
Starting Broker in-process...
Successfully started Broker in-process
Connecting to Local Broker...
Successfully connected to Local Broker
Starting IDB Local Agent...
Successfully started IDB Local Agent
Checking xma 17.7.0.223 installation...
Checking host configuration for connecting to 'WORKSTATION'...
Checking SSH configuration...
Current SSH Key File: C:\Users\USER\AppData\Local\Xamarin\MonoTouch\id_xma.pub
Initializing environment...
Checking available disk space...
Checking if Rosetta is installed...
Checking Mono installation...
Checking host configuration for connecting to 'WORKSTATION'...
Host 'WORKSTATION' is configured correctly
Starting connection to 'WORKSTATION'...
Checking Broker 17.7.0.223 installation...
Starting Broker 17.7.0.223 in port 54483...
Broker 17.7.0.223 started successfully
Starting connection to 'WORKSTATION'...
SSH connection to 'WORKSTATION' has been established...
Starting registered Agents: IDB 17.7.0.223...
Starting IDB 17.7.0.223...
Checking IDB 17.7.0.223 installation...
Starting IDB 17.7.0.223 in port 54483...
IDB 17.7.0.223 started successfully
IDB 17.7.0.223 started
Starting registered Agents: ...
The Agents have been started successfully
Performing server validations against 'WORKSTATION'...
Installing dotnet SDK '7.0.403-servicing.23520.24'...
Downloading dotnet-install script...
Could not download the latest dotnet-install script. Details: Error: ConnectFailure (Connection refused)
Connection refused

Using dotnet install script '/Users/admin/Library/Caches/Xamarin/XMA/SDKs/dotnet/scripts/dotnet-install.sh'...
--install-dir /Users/admin/Library/Caches/Xamarin/XMA/SDKs/dotnet --version 7.0.403-servicing.23520.24 --architecture Arm64 --no-path
dotnet-install: Attempting to download using primary link https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/dotnet-sdk-7.0.403-servicing.23520.24-osx-arm64.tar.gz
curl: (7) Failed to connect to dotnetcli.azureedge.net port 443 after 4 ms: Couldn't connect to server
/Users/admin/Library/Caches/Xamarin/XMA/SDKs/dotnet/scripts/dotnet-install.sh: line 1024: http_code: unbound variable

Could not install dotnet SDK '7.0.403-servicing.23520.24'. Details:

**Comment by YuliiaKovalova** [comment]
@ImGonaRot, May I ask you to repro this issue apart from Xamarin installation?
1. Download a script from https://dot.net/v1/dotnet-install.sh (the source is taken from here https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)
2. Open a command line
3. Navigate to the download location
4. Invoke :
"./dotnet-install.sh --install-dir /Users/USER/Library/Caches/Xamarin/XMA/SDKs/dotnet --version 7.0.403-servicing.23520.24 --architecture Arm64 --no-path --verbose"

**Comment by ImGonaRot** [comment]
@YuliiaKovalova Here is the verbos log directly from the Mac terminal.
Sorry for the long text.

USER@WJWORKSTATION2 scripts % sudo sh dotnet-install.sh --install-dir /Users/USER/Library/Caches/Xamarin/XMA/SDKs/dotnet --version 7.0.403-servicing.23520.24 --architecture Arm64 --no-path --verbose
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without USER rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Calling: machine_has curl
dotnet-install: Calling: calculate_vars 
dotnet-install: Calling: get_normalized_architecture_from_architecture Arm64
dotnet-install: Normalized architecture: 'arm64'.
dotnet-install: Calling: get_normalized_os 
dotnet-install: Calling: get_current_os_name 
dotnet-install: Normalized OS: 'osx'.
dotnet-install: Calling: get_normalized_quality 
dotnet-install: Normalized quality: ''.
dotnet-install: Calling: get_normalized_channel LTS
dotnet-install: Normalized channel: 'LTS'.
dotnet-install: Calling: get_normalized_product 
dotnet-install: Normalized product: 'dotnet-sdk'.
dotnet-install: Calling: resolve_installation_path /Users/USER/Library/Caches/Xamarin/XMA/SDKs/dotnet
dotnet-install: InstallRoot: '/Users/USER/Library/Caches/Xamarin/XMA/SDKs/dotnet'.
dotnet-install: Calling: get_normalized_architecture_for_specific_sdk_version 7.0.403-servicing.23520.24 LTS arm64
dotnet-install: Calling: get_current_os_name 
dotnet-install: Calling: get_specific_version_from_version https://dotnetcli.azureedge.net/dotnet LTS arm64 7.0.403-servicing.23520.24 
dotnet-install: Calling: get_specific_product_version https://dotnetcli.azureedge.net/dotnet 7.0.403-servicing.23520.24
dotnet-install: Calling: get_specific_product_version_url https://dotnetcli.azureedge.net/dotnet 7.0.403-servicing.23520.24 true 
dotnet-install: Constructed productVersion link: https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/sdk-productVersion.txt
dotnet-install: Calling: get_specific_product_version_url https://dotnetcli.azureedge.net/dotnet 7.0.403-servicing.23520.24 false 
dotnet-install: Constructed productVersion link: https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/productVersion.txt
dotnet-install: Checking for the existence of https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/sdk-productVersion.txt
dotnet-install: Calling: machine_has curl
dotnet-install: Checking for the existence of https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/productVersion.txt
dotnet-install: Calling: machine_has curl
dotnet-install: Failed to get the version using productVersion.txt file. Download link will be parsed instead.
dotnet-install: Calling: get_product_specific_version_from_download_link  7.0.403-servicing.23520.24
dotnet-install: specific_version=7.0.403-servicing.23520.24
dotnet-install: Calling: construct_download_link https://dotnetcli.azureedge.net/dotnet LTS arm64 7.0.403-servicing.23520.24 osx
dotnet-install: Calling: get_specific_product_version https://dotnetcli.azureedge.net/dotnet 7.0.403-servicing.23520.24
dotnet-install: Calling: get_specific_product_version_url https://dotnetcli.azureedge.net/dotnet 7.0.403-servicing.23520.24 true 
dotnet-install: Constructed productVersion link: https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/sdk-productVersion.txt
dotnet-install: Calling: get_specific_product_version_url https://dotnetcli.azureedge.net/dotnet 7.0.403-servicing.23520.24 false 
dotnet-install: Constructed productVersion link: https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/productVersion.txt
dotnet-install: Checking for the existence of https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/sdk-productVersion.txt
dotnet-install: Calling: machine_has curl
dotnet-install: Checking for the existence of https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/productVersion.txt
dotnet-install: Calling: machine_has curl
dotnet-install: Failed to get the version using productVersion.txt file. Download link will be parsed instead.
dotnet-install: Calling: get_product_specific_version_from_download_link  7.0.403-servicing.23520.24
dotnet-install: Constructed primary named payload URL: https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/dotnet-sdk-7.0.403-servicing.23520.24-osx-arm64.tar.gz
dotnet-install: Calling: construct_legacy_download_link https://dotnetcli.azureedge.net/dotnet LTS arm64 7.0.403-servicing.23520.24
dotnet-install: Calling: get_legacy_os_name 
dotnet-install: Constructed legacy named payload URL: https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/dotnet-dev-osx-arm64.7.0.403-servicing.23520.24.tar.gz
dotnet-install: Calling: is_dotnet_package_installed /Users/USER/Library/Caches/Xamarin/XMA/SDKs/dotnet sdk 7.0.403-servicing.23520.24
dotnet-install: Calling: combine_paths /Users/USER/Library/Caches/Xamarin/XMA/SDKs/dotnet sdk
dotnet-install: combine_paths: root_path=/Users/USER/Library/Caches/Xamarin/XMA/SDKs/dotnet
dotnet-install: combine_paths: child_path=sdk
dotnet-install: Calling: combine_paths /Users/USER/Library/Caches/Xamarin/XMA/SDKs/dotnet/sdk 7.0.403-servicing.23520.24
dotnet-install: combine_paths: root_path=/Users/USER/Library/Caches/Xamarin/XMA/SDKs/dotnet/sdk
dotnet-install: combine_paths: child_path=7.0.403-servicing.23520.24
dotnet-install: is_dotnet_package_installed: dotnet_package_path=/Users/USER/Library/Caches/Xamarin/XMA/SDKs/dotnet/sdk/7.0.403-servicing.23520.24
dotnet-install: Calling: get_specific_version_from_version https://dotnetbuilds.azureedge.net/public LTS arm64 7.0.403-servicing.23520.24 
dotnet-install: Calling: get_specific_product_version https://dotnetbuilds.azureedge.net/public 7.0.403-servicing.23520.24
dotnet-install: Calling: get_specific_product_version_url https://dotnetbuilds.azureedge.net/public 7.0.403-servicing.23520.24 true 
dotnet-install: Constructed productVersion link: https://dotnetbuilds.azureedge.net/public/Sdk/7.0.403-servicing.23520.24/sdk-productVersion.txt
dotnet-install: Calling: get_specific_product_version_url https://dotnetbuilds.azureedge.net/public 7.0.403-servicing.23520.24 false 
dotnet-install: Constructed productVersion link: https://dotnetbuilds.azureedge.net/public/Sdk/7.0.403-servicing.23520.24/productVersion.txt
dotnet-install: Checking for the existence of https://dotnetbuilds.azureedge.net/public/Sdk/7.0.403-servicing.23520.24/sdk-productVersion.txt
dotnet-install: Calling: machine_has curl
dotnet-install: Checking for the existence of https://dotnetbuilds.azureedge.net/public/Sdk/7.0.403-servicing.23520.24/productVersion.txt
dotnet-install: Calling: machine_has curl
dotnet-install: Failed to get the version using productVersion.txt file. Download link will be parsed instead.
dotnet-install: Calling: get_product_specific_version_from_download_link  7.0.403-servicing.23520.24
dotnet-install: specific_version=7.0.403-servicing.23520.24
dotnet-install: Calling: construct_download_link https://dotnetbuilds.azureedge.net/public LTS arm64 7.0.403-servicing.23520.24 osx
dotnet-install: Calling: get_specific_product_version https://dotnetbuilds.azureedge.net/public 7.0.403-servicing.23520.24
dotnet-install: Calling: get_specific_product_version_url https://dotnetbuilds.azureedge.net/public 7.0.403-servicing.23520.24 true 
dotnet-install: Constructed productVersion link: https://dotnetbuilds.azureedge.net/public/Sdk/7.0.403-servicing.23520.24/sdk-productVersion.txt
dotnet-install: Calling: get_specific_product_version_url https://dotnetbuilds.azureedge.net/public 7.0.403-servicing.23520.24 false 
dotnet-install: Constructed productVersion link: https://dotnetbuilds.azureedge.net/public/Sdk/7.0.403-servicing.23520.24/productVersion.txt
dotnet-install: Checking for the existence of https://dotnetbuilds.azureedge.net/public/Sdk/7.0.403-servicing.23520.24/sdk-productVersion.txt
dotnet-install: Calling: machine_has curl
dotnet-install: Checking for the existence of https://dotnetbuilds.azureedge.net/public/Sdk/7.0.403-servicing.23520.24/productVersion.txt
dotnet-install: Calling: machine_has curl
dotnet-install: Failed to get the version using productVersion.txt file. Download link will be parsed instead.
dotnet-install: Calling: get_product_specific_version_from_download_link  7.0.403-servicing.23520.24
dotnet-install: Constructed primary named payload URL: https://dotnetbuilds.azureedge.net/public/Sdk/7.0.403-servicing.23520.24/dotnet-sdk-7.0.403-servicing.23520.24-osx-arm64.tar.gz
dotnet-install: Calling: construct_legacy_download_link https://dotnetbuilds.azureedge.net/public LTS arm64 7.0.403-servicing.23520.24
dotnet-install: Calling: get_legacy_os_name 
dotnet-install: Constructed legacy named payload URL: https://dotnetbuilds.azureedge.net/public/Sdk/7.0.403-servicing.23520.24/dotnet-dev-osx-arm64.7.0.403-servicing.23520.24.tar.gz
dotnet-install: Calling: is_dotnet_package_installed /Users/USER/Library/Caches/Xamarin/XMA/SDKs/dotnet sdk 7.0.403-servicing.23520.24
dotnet-install: Calling: combine_paths /Users/USER/Library/Caches/Xamarin/XMA/SDKs/dotnet sdk
dotnet-install: combine_paths: root_path=/Users/USER/Library/Caches/Xamarin/XMA/SDKs/dotnet
dotnet-install: combine_paths: child_path=sdk
dotnet-install: Calling: combine_paths /Users/USER/Library/Caches/Xamarin/XMA/SDKs/dotnet/sdk 7.0.403-servicing.23520.24
dotnet-install: combine_paths: root_path=/Users/USER/Library/Caches/Xamarin/XMA/SDKs/dotnet/sdk
dotnet-install: combine_paths: child_path=7.0.403-servicing.23520.24
dotnet-install: is_dotnet_package_installed: dotnet_package_path=/Users/USER/Library/Caches/Xamarin/XMA/SDKs/dotnet/sdk/7.0.403-servicing.23520.24
dotnet-install: Generated 4 links.
dotnet-install: Link 0: primary, 7.0.403-servicing.23520.24, https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/dotnet-sdk-7.0.403-servicing.23520.24-osx-arm64.tar.gz
dotnet-install: Link 1: legacy, 7.0.403-servicing.23520.24, https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/dotnet-dev-osx-arm64.7.0.403-servicing.23520.24.tar.gz
dotnet-install: Link 2: primary, 7.0.403-servicing.23520.24, https://dotnetbuilds.azureedge.net/public/Sdk/7.0.403-servicing.23520.24/dotnet-sdk-7.0.403-servicing.23520.24-osx-arm64.tar.gz
dotnet-install: Link 3: legacy, 7.0.403-servicing.23520.24, https://dotnetbuilds.azureedge.net/public/Sdk/7.0.403-servicing.23520.24/dotnet-dev-osx-arm64.7.0.403-servicing.23520.24.tar.gz
dotnet-install: Calling: install_dotnet 
dotnet-install: Zip path: /tmp/dotnet.NwB5hp63L
dotnet-install: Attempting to download using primary link https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/dotnet-sdk-7.0.403-servicing.23520.24-osx-arm64.tar.gz
dotnet-install: Calling: download https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/dotnet-sdk-7.0.403-servicing.23520.24-osx-arm64.tar.gz /tmp/dotnet.NwB5hp63L
dotnet-install: Calling: machine_has curl
dotnet-install: Calling: downloadcurl https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/dotnet-sdk-7.0.403-servicing.23520.24-osx-arm64.tar.gz /tmp/dotnet.NwB5hp63L
curl: (7) Failed to connect to dotnetcli.azureedge.net port 443 after 4 ms: Couldn't connect to server
dotnet-install: Unable to download https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/dotnet-sdk-7.0.403-servicing.23520.24-osx-arm64.tar.gz. Failed to reach the server: connection timeout.
dotnet-install.sh: line 1024: http_code: unbound variable

**Comment by YuliiaKovalova** [comment]
@ImGonaRot , thank you for the Vesbose log, it's exactly what we need. We are investigating this issue.

**Comment by ImGonaRot** [comment]
@YuliiaKovalova  
Well this was a problem with the Mac.
Our network has been using a proxy server for 3 years now but today, the SH scripts on the Mac decided to stop working when calling curl commands.
The fix was to do the following on the Mac:
1. drop to terminal
2. cd ~
3. nano .curlrc
4. proxy="http://ourproxy"
5. write file and exit

Sorry for listing this as a problem.

**Comment by YuliiaKovalova** [comment]
@ImGonaRot , thank you for letting us know and attaching the workaround.
I can be handy for other customers!

**Comment by UkeHa** [comment]
@YuliiaKovalova i ran into the same issue on .net 8.0.401 (both on PC and Mac). First i get this error:

> The dotnet SDK installation '8.0.401-servicing.24412.2' has failed. If a retry does not work, please refer to the public documentation for more information and troubleshooting: https://aka.ms/pairtomac/dotnet

Followed by:

>Could not install dotnet SDK '8.0.401-servicing.24412.2'. Details: IO_PathNotFound_Path, /Users/{myuser}/Library/Caches/Xamarin/XMA/Agents/IDB/17.11.0.95/Contents/MonoBundle/.xamarin/osx-arm64/Scripts/dotnet-install.sh

Running a similar command as your previously mentioned workaround

`sh /Users/{myuser}/Downloads/dotnet-install.sh  --install-dir /Users/{myuser}/Library/Caches/Xamarin/XMA/SDKs/dotnet --version 8.0.401-servicing.24412.2 --architecture Arm64 --no-path --verbose`
<details><summary>Summary of shell output</summary>
<p>

```shell
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Calling: machine_has curl
dotnet-install: Calling: calculate_vars 
dotnet-install: Calling: get_normalized_architecture_from_architecture Arm64
dotnet-install: Normalized architecture: 'arm64'.
dotnet-install: Calling: get_normalized_os 
dotnet-install: Calling: get_current_os_name 
dotnet-install: Normalized OS: 'osx'.
dotnet-install: Calling: get_normalized_quality 
dotnet-install: Normalized quality: ''.
dotnet-install: Calling: get_normalized_channel LTS
dotnet-install: Normalized channel: 'LTS'.
dotnet-install: Calling: get_normalized_product 
dotnet-install: Normalized product: 'dotnet-sdk'.
dotnet-install: Calling: resolve_installation_path /Users/{myuser}/Library/Caches/Xamarin/XMA/SDKs/dotnet
dotnet-install: InstallRoot: '/Users/{myuser}/Library/Caches/Xamarin/XMA/SDKs/dotnet'.
dotnet-install: Calling: get_normalized_architecture_for_specific_sdk_version 8.0.401-servicing.24412.2 LTS arm64
dotnet-install: Calling: get_current_os_name 
dotnet-install: Calling: get_specific_version_from_version https://dotnetcli.azureedge.net/dotnet LTS arm64 8.0.401-servicing.24412.2 
dotnet-install: Calling: get_specific_product_version https://dotnetcli.azureedge.net/dotnet 8.0.401-servicing.24412.2
dotnet-install: Calling: get_specific_product_version_url https://dotnetcli.azureedge.net/dotnet 8.0.401-servicing.24412.2 true 
dotnet-install: Constructed productVersion link: https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.401-servicing.24412.2/sdk-productVersion.txt
dotnet-install: Calling: get_specific_product_version_url https://dotnetcli.azureedge.net/dotnet 8.0.401-servicing.24412.2 false 
dotnet-install: Constructed productVersion link: https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.401-servicing.24412.2/productVersion.txt
dotnet-install: Checking for the existence of https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.401-servicing.24412.2/sdk-productVersion.txt
dotnet-install: Calling: machine_has curl
dotnet-install: specific_version=8.0.401-servicing.24412.2
dotnet-install: Calling: construct_download_link https://dotnetcli.azureedge.net/dotnet LTS arm64 8.0.401-servicing.24412.2 osx
dotnet-install: Calling: get_specific_product_version https://dotnetcli.azureedge.net/dotnet 8.0.401-servicing.24412.2
dotnet-install: Calling: get_specific_product_version_url https://dotnetcli.azureedge.net/dotnet 8.0.401-servicing.24412.2 true 
dotnet-install: Constructed productVersion link: https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.401-servicing.24412.2/sdk-productVersion.txt
dotnet-install: Calling: get_specific_product_version_url https://dotnetcli.azureedge.net/dotnet 8.0.401-servicing.24412.2 false 
dotnet-install: Constructed productVersion link: https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.401-servicing.24412.2/productVersion.txt
dotnet-install: Checking for the existence of https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.401-servicing.24412.2/sdk-productVersion.txt
dotnet-install: Calling: machine_has curl
dotnet-install: Constructed primary named payload URL: https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.401-servicing.24412.2/dotnet-sdk-8.0.401-osx-arm64.tar.gz
dotnet-install: Calling: construct_legacy_download_link https://dotnetcli.azureedge.net/dotnet LTS arm64 8.0.401-servicing.24412.2
dotnet-install: Calling: get_legacy_os_name 
dotnet-install: Constructed legacy named payload URL: https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.401-servicing.24412.2/dotnet-dev-osx-arm64.8.0.401-servicing.24412.2.tar.gz
dotnet-install: Calling: is_dotnet_package_installed /Users/{myuser}/Library/Caches/Xamarin/XMA/SDKs/dotnet sdk 8.0.401
dotnet-install: Calling: combine_paths /Users/{myuser}/Library/Caches/Xamarin/XMA/SDKs/dotnet sdk
dotnet-install: combine_paths: root_path=/Users/{myuser}/Library/Caches/Xamarin/XMA/SDKs/dotnet
dotnet-install: combine_paths: child_path=sdk
dotnet-install: Calling: combine_paths /Users/{myuser}/Library/Caches/Xamarin/XMA/SDKs/dotnet/sdk 8.0.401
dotnet-install: combine_paths: root_path=/Users/{myuser}/Library/Caches/Xamarin/XMA/SDKs/dotnet/sdk
dotnet-install: combine_paths: child_path=8.0.401
dotnet-install: is_dotnet_package_installed: dotnet_package_path=/Users/{myuser}/Library/Caches/Xamarin/XMA/SDKs/dotnet/sdk/8.0.401
dotnet-install: .NET Core SDK with version '8.0.401' is already installed.
``` 


</p>
</details> 

Running the same request as root (via sudo) results in a different message, but returns that the Installation finished successfully.

When pairing with the mac from the latest Visual Studio (17.11.3) the connection still fails, but interestingly seems to send a container (.app.95?) that when i open it contains all the necessary files? Extracting manually does not help with connecting.

![grafik](https://github.com/user-attachments/assets/09b60abf-1aef-41a0-83df-5672ee3c4b2e)


Installing .net9-rc1, i can connect to the mac but the maui workload for ios goes missing. Restoring it, somehow breaks some references and won't build the solution. So this isn't really a workaround as well.

Should this be posted into a new issue and if so, which Microsoft bugtracker would be the best fit? Visual Studio, dotnet or MAUI?

**Comment by YuliiaKovalova** [comment]
cc: @baronfel

**Comment by baronfel** [comment]
@UkeHa please start with a Visual Studio Developer Community ticket - it's possible the Pair to Mac feature of VS has a bug, but this repo is merely an internal implementation detail of whatever functionality that team has implemented. They would need to triage their usage of our script to see if they need to change the way they call us or deploy us.
