### ISSUE TITLE
dotnet-install.ps1 pointing to missing bits

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/install-scripts#63]
The dotnet/performance repo pulls down 5.0 from https://dot.net/v1/dotnet-install.ps1 which redirects to https://dotnet.microsoft.com/download/dotnet-core/scripts/v1/dotnet-install.ps1

Currently this points to nonexistent bits.

```
C:\git\performance>curl -o dotnet-install.ps1 https://dotnet.microsoft.com/download/dotnet-core/scripts/v1/dotnet-install.ps1
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 39736 100 39736 0 0 39736 0 0:00:01 --:--:-- 0:00:01 497k

C:\git\performance>powershell.exe -NoProfile -ExecutionPolicy Bypass ./dotnet-install.ps1 -InstallDir C:\git\performance\tools\dotnet\x64 -Architecture x64 -Channel master
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-rc.1.20403.14/dotnet-sdk-5.0.100-rc.1.20403.14-win-x64.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-rc.1.20403.14/dotnet-sdk-5.0.100-rc.1.20403.14-win-x64.zip
dotnet-install: Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-rc.1.20403.14/dotnet-dev-win-x64.5.0.100-rc.1.20403.14.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-rc.1.20403.14/dotnet-dev-win-x64.5.0.100-rc.1.20403.14.zip
Could not find/download: ".NET Core SDK" with version = 5.0.100-rc.1.20403.14
Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
At C:\git\performance\tools\dotnet\x64\dotnet-install.ps1:664 char:5
+ throw "Could not find/download: `"$assetName`" with version = $Sp ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : OperationStopped: (Could not find/...ET Core support:String) [], RuntimeException
+ FullyQualifiedErrorId : Could not find/download: ".NET Core SDK" with version = 5.0.100-rc.1.20403.14
Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
```

cc @donJoseLuis

**Comment by danmosemsft** [comment]
A workaround is to choose `-Version 5.0.100-rc.1.20403.5` (gotten from https://github.com/dotnet/installer)

**Comment by danmosemsft** [comment]
cc @DrewScoggins as I get this running the perf repo workflow:
```
C:\git\performance>py ..\performance\scripts\benchmarks_ci.py -f netcoreapp3.1 netcoreapp5.0 --filter "System.Collections.IterateForEach<Int32>.ConcurrentBag*"
...
[2020/08/03 15:21:38][INFO] $ powershell.exe -NoProfile -ExecutionPolicy Bypass C:\git\performance\tools\dotnet\x64\dotnet-install.ps1 -InstallDir C:\git\performance\tools\dotnet\x64 -Architecture x64 -Channel master
[2020/08/03 15:21:39][INFO] dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-rc.1.20403.14/dotnet-sdk-5.0.100-rc.1.20403.14-win-x64.zip
[2020/08/03 15:21:41][INFO] dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-rc.1.20403.14/dotnet-sdk-5.0.100-rc.1.20403.14-win-x64.zip
[2020/08/03 15:21:41][INFO] dotnet-install: Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-rc.1.20403.14/dotnet-dev-win-x64.5.0.100-rc.1.20403.14.zip
[2020/08/03 15:21:43][INFO] dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-rc.1.20403.14/dotnet-dev-win-x64.5.0.100-rc.1.20403.14.zip
[2020/08/03 15:21:43][INFO] Could not find/download: ".NET Core SDK" with version = 5.0.100-rc.1.20403.14
[2020/08/03 15:21:43][INFO] Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
[2020/08/03 15:21:43][INFO] At C:\git\performance\tools\dotnet\x64\dotnet-install.ps1:664 char:5
[2020/08/03 15:21:43][INFO] +     throw "Could not find/download: `"$assetName`" with version = $Sp ...
[2020/08/03 15:21:43][INFO] +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2020/08/03 15:21:43][INFO]     + CategoryInfo          : OperationStopped: (Could not find/...ET Core support:String) [], RuntimeException
[2020/08/03 15:21:43][INFO]     + FullyQualifiedErrorId : Could not find/download: ".NET Core SDK" with version = 5.0.100-rc.1.20403.14
[2020/08/03 15:21:43][INFO] Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
[2020/08/03 15:21:43][INFO]
```

**Comment by danmosemsft** [comment]
@donJoseLuis this morning this points to `https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-rc.1.20404.3/dotnet-sdk-5.0.100-rc.1.20404.3-win-x64.zip` which exists so we're going again. But I think it's important that dotnet-install.ps1 never point to a nonexistent build when another is available. This is because we have infrastructure that relies on it (as do customers). Thoughts?

**Comment by DrewScoggins** [comment]
Dan, was this in the runtime repo? Because we just parse the dotnet version that lives in global.json and use that as the version we try and download.

**Comment by DrewScoggins** [comment]
Also we have had many issues when trying to pull from the tip of master, which is why we moved to the LKG model.

**Comment by danmosemsft** [comment]
@DrewScoggins no, I hit this doing a command like `C:\git\performance>py ..\performance\scripts\benchmarks_ci.py -f netcoreapp3.1 netcoreapp5.0 --filter "System.Collections.IterateForEach<Int32>.ConcurrentBag*"` (ie., in the perf repo)

I'm simply running the repro command from one of the runtime perf issues. (With the quoting and semicolon typos fixed in it)

**Comment by donJoseLuis** [comment]
@danmosemsft  greetings.  Thanks for creating the issue & letting us know about it.  I see that you have a work around.  Please allow us to look into this Prague time tomorrow.

**Comment by donJoseLuis** [comment]
@bozturkMSFT let's discuss in our 8/5 stand up.

**Comment by donJoseLuis** [comment]
Greetings @danmosemsft  Y @DrewScoggins ,

causes of the problem:
1. copy-to-latest overwrites a “latest” in the dotnetcli storage account that dotnet-install knows how to access
1. dependency flow is based on association of builds with channels
1. The relevant branch (one off private build) never automatically publishes bits to repos

Tracked in https://github.com/dotnet/installer/pull/8092

We'll update the scripts as part of our current resiliency improvement initiative, which we plan to deliver by the end of the month.

**Comment by bozturkMSFT** [comment]
A fix for the major cause of these kinds of issues has been recently merged: https://github.com/dotnet/installer/pull/8092
This should make sure that the bits are being uploaded to the correct channel. 

Issues are still possible, though, if [dotnet/installer](https://www.github.com/dotnet/installer) build pipeline fails during the stage where the bits are uploaded to the blob storage.
